apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pvc
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/ubuntu/pv-minio
  volumeMode: Filesystem
  claimRef:
    namespace: kubeflow
    name: minio-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-claim
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/ubuntu/pv-mysql
  volumeMode: Filesystem
  claimRef:
    namespace: kubeflow
    name: mysql-pv-claim
