apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-all4dich-gmail-com-clusterrole-admin
  namespace: all4dich
  annotations:
    role: ClusterRole/kubeflow-admin
    user: all4dich@gmail.com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: all4dich@gmail.com
